// <auto-generated />
using System;
using LondonStockAPI.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LondonStockAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117094844_addRelationships")]
    partial class addRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LondonStockAPI.Entity.Broker", b =>
                {
                    b.Property<int>("BrokerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrokerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrokerId");

                    b.ToTable("Broker");

                    b.HasData(
                        new
                        {
                            BrokerId = 1,
                            Name = "Zerodha"
                        },
                        new
                        {
                            BrokerId = 2,
                            Name = "Upstox"
                        });
                });

            modelBuilder.Entity("LondonStockAPI.Entity.Stocks", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ticker");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Ticker = "AAPL",
                            Name = "Apple Inc."
                        },
                        new
                        {
                            Ticker = "MSFT",
                            Name = "Microsoft Corp."
                        },
                        new
                        {
                            Ticker = "GOOGL",
                            Name = "Alphabet Inc"
                        },
                        new
                        {
                            Ticker = "F",
                            Name = "Ford Motor Company"
                        },
                        new
                        {
                            Ticker = "TSLA",
                            Name = "Tesla, Inc."
                        },
                        new
                        {
                            Ticker = "WMT",
                            Name = "Walmart"
                        });
                });

            modelBuilder.Entity("LondonStockAPI.Entity.Trades", b =>
                {
                    b.Property<long>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TradeId"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Shares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TradedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("Ticker");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("LondonStockAPI.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("LondonStockAPI.Entity.Trades", b =>
                {
                    b.HasOne("LondonStockAPI.Entity.Broker", "Broker")
                        .WithMany("Trades")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LondonStockAPI.Entity.Stocks", "Stocks")
                        .WithMany("Trades")
                        .HasForeignKey("Ticker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("LondonStockAPI.Entity.Broker", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("LondonStockAPI.Entity.Stocks", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
